
[theme]
primaryColor = "#c1820eff"              # Laranja (botões, sliders, seletores)
backgroundColor = "#800080"        
secondaryBackgroundColor = "#707e70ff" # Laranja médio (caixas internas, cards)
textColor = "#ffffffff"                 # Texto preto para contraste
font = "sans serif"
